

services:

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    restart: always

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
        
  gateway-service:
    build: ./gateway-service
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - task-service


  event-queue-service:
    build: ./event-queue-service
    ports:
      - "3004:3004"
    depends_on:
      - redis
    restart: always

  auth-service:
    build: ./auth-service
    ports:
      - "3002:3002"
    restart: always

  task-service:
    build: ./task-service
    ports:
      - "3001:3001"
    restart: always

  notifier-service:
    build: ./notifier-service
    ports:
      - "3005:3005"
    restart: always
    depends_on:
      - redis

